In [2]:
#This is the main algorithm of K-Means Clustering
#We are going to build a simple example
#that including building our data base
#as well as develop the main algorithm
#Step 1: Importing our dependencies
from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
# This one help us calculate the Euclid distance best
from scipy.spatial.distance import cdist 
import random
np.random.seed(18)

In [43]:
#Step 2: Creating our database
#This is our centroid (The labels so we can check the results)
means = [[2,2],[8,3],[3,6]] 
cov = [[1,0],[0,1]]

#Now we are going to generate points around the centroids 
N = 500
X0 = np.random.multivariate_normal(means[0],cov,N) #we gonna have 500 points with 2D around means[0]
X1 = np.random.multivariate_normal(means[1],cov,N) #we gonna have 500 points with 2D around means[1]
X2 = np.random.multivariate_normal(means[2],cov,N) #we gonna have 500 points with 2D around means[2]

#Now we combine all of them into one sigle plane
X = np.concatenate((X0,X1,X2), axis = 0)
K = 3 # 3 clusters
#Give the given input its labels and push them into 
#an array original labels
original_label = np.asarray([0]*N + [1]*N + [2]*N).T

In [51]:
#Step 3: We now can develop the algorithm to find our
#Centroid with the above data
#Step 3.1: randomly choose the centroids
def kmeans_init_centroids(X,k):
    #Pick randomly k = 3 centroid inside the X matrix
    #Because np.random.choice(X.shape[0],K, replace = False) only return 
    #The index of the X.Shape[0] so we have to use X[]
    return X[np.random.choice(X.shape[0],K, replace = False)]
#Find the label for data with the centroids
def kmeans_assign_labels(X,centroids):
    D = cdist(X,centroids)
    #From here, 1 point will have 3 distances with 
    #3 centroids so
    #Then we give back the index of the closest 
    return np.argmin(D, axis = 1)
#So now after that we will have to update the centroids
def kmeans_update_centroids(X, labels , K):
    #Initiate 3 centroids with 2-D
    centroids = np.zeros((K,X.shape[1]))
    for k in range(K):
        #Collect all points that have label k
        Xk = X[labels == k , :]
        centroids[k,:]  = np.mean(Xk, axis = 0)
    return centroids
#We also need to have some conditions to stop the algorithm
def has_converged(centroids, new_centroids):
    #This means that when we cannot update the centroids any more
    return (set([tuple(a) for a in centroids]) == set([tuple(a) for a in new_centroids]))

In [52]:
#Step 4: Now after developed our function
#We can combine them and make our K-Means
#This have matrix X and K clusters
def kmeans(X,K):
    #random pick centroids by
    centroids = [kmeans_init_centroids(X,K)]
    labels = []
    it = 0
    
    #Now we give the labels
    while True:
        print(centroids[-1])
        labels.append(kmeans_assign_labels(X, centroids[-1]))
        new_centroids = kmeans_update_centroids(X,labels[-1],K)
        if has_converged(centroids[-1], new_centroids):
            break
        centroids.append(new_centroids)
        it += 1
    return (centroids, labels, it)

(centroids, labels, it) = kmeans(X, K)
centroids[-1]

[[3.78165693 2.16432607]
 [2.71495256 4.81373136]
 [8.7384328  2.98644565]]
[[2.37454936 1.77942091]
 [2.75504223 5.48223065]
 [8.07887557 3.07763498]]
[[2.00984159 1.97572133]
 [2.99310364 5.8557976 ]
 [7.98105766 3.061898  ]]
[[2.00926148 2.04057779]
 [3.02677331 5.92271342]
 [7.98105766 3.061898  ]]
[[2.01155636 2.05639698]
 [3.03260687 5.9379209 ]
 [7.98105766 3.061898  ]]


array([[2.01155636, 2.05639698],
       [3.03260687, 5.9379209 ],
       [7.98105766, 3.061898  ]])

In [54]:
#Now we can check the result by using the scikit learn
from sklearn.cluster import KMeans
model = KMeans(n_clusters = 3, random_state = 0).fit(X)
print("Center found by sk.learn is ")
print(model.cluster_centers_)

Center found by sk.learn is 
[[7.98105766 3.061898  ]
 [3.03260687 5.9379209 ]
 [2.01155636 2.05639698]]
