In [1]:
#Step 1 : always set up our dependencies first
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [21]:
#Step 2: We now seperate our data
iris = datasets.load_iris()
#total data we have including 4 differnent character
#that we will use to analyze the model
iris_x = iris.data 
#total label of the data
iris_y = iris.target

print('Number of classes : %d ' %len(np.unique(iris_y)))
print("Number of data point : %d" %len(iris_y))

X0 = iris_x[iris_y == 0,:]
print("\nFirst 5 samples from class 0 :\n" ,X0[:5,])

X1 = iris_x[iris_y == 1,:]
print("\nFirst 5 samples from class 1 :\n" ,X1[:5,])

X2 = iris_x[iris_y == 2,:]
print("\nFirst 5 samples from class 2 :\n" ,X2[:5,])


Number of classes : 3 
Number of data point : 150

First 5 samples from class 0 :
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

First 5 samples from class 1 :
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

First 5 samples from class 2 :
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]
150
150


In [22]:
#Step 3: We are now dividing our datasets into training and testing sets
#Now we know that we have 150 different datapoints in our datasets
#assume that we want to have 50 datapoints for testing and 100 datapoints for testings
#So we can devide the divide the datasets we have by using 
# sklearn library
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris_x,iris_y,test_size = 50)
print("Trainning size ",len(y_train))
print("Testing size ",len(y_test))
#After this we have 50 testing points and 100 training points 
#with label y corresponding to them

Trainning size  100
Testing size  50


In [27]:
#Step4.1: We now assuming that K = 1. 
# This means we use one point of training data and take the label to predict for the
#testing point
clf = neighbors.KNeighborsClassifier(n_neighbors = 1, p = 2)
#traning the model with the coressponding 
#data and its labels
clf.fit(X_train,y_train)
#Now we compute our prediction with the X_test set
y_pred = clf.predict(X_test)

#then we now try to compare the result from our prediction
#with the actual results y_test

print("Print the result of 20 test data points: ")
print("Our prediction from the y_pred    :" , y_pred[20:40])
print("Our correct result from the y_test:" , y_test[20:40])

Print the result of 20 test data points: 
Our prediction from the y_pred    : [0 0 1 2 2 1 1 1 0 0 2 0 0 2 2 0 1 1 2 0]
Our correct result from the y_test: [0 0 1 2 2 1 2 1 0 0 2 0 0 2 2 0 1 1 2 0]


In [34]:
#Step 5 : Evaluation method:
#We can you another library from the sklearn
from sklearn.metrics import accuracy_score
print("The accuracy of our model is %f"  %(100*accuracy_score(y_test,y_pred)))


The accuracy of our model is 98.000000


In [35]:
#Step 4.2: We try to optimize our model by
#increasing the number of neighbors that
#we will increase the n_neighbor =10
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2)
#traning the model with the coressponding 
#data and its labels
clf.fit(X_train,y_train)
#Now we compute our prediction with the X_test set
y_pred = clf.predict(X_test)
print("The accuracy of our model is %f"  %(100*accuracy_score(y_test,y_pred)))

The accuracy of our model is 96.000000


In [42]:
#Step 6: Then we try to optimize the productivity of the
#model by letting the point that close to neighbor
#to have bigger weights (this is fair)
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance')
#traning the model with the coressponding 
#data and its labels
clf.fit(X_train,y_train)
#Now we compute our prediction with the X_test set
y_pred = clf.predict(X_test)
print("The accuracy of our model is %f"  %(100*accuracy_score(y_test,y_pred)))

The accuracy of our model is 98.000000


In [44]:
#Step 7: now we can also calculate our own
#weights by create a small function and 
#add it to the clf 

def myweight(distances):
    sigma2 = .5
    return np.exp(-distances**2/sigma2)
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = myweight)
#traning the model with the coressponding 
#data and its labels
clf.fit(X_train,y_train)
#Now we compute our prediction with the X_test set
y_pred = clf.predict(X_test)
print("The accuracy of our model is %f"  %(100*accuracy_score(y_test,y_pred)))

The accuracy of our model is 98.000000
